import React, {useState} from 'react'
import { useNavigate } from 'react-router-dom'
import { preview } from '../assets/assets'
import { getRandomPrompt } from '../utils';
import { FormField, Loader } from '../components';

const CreatePost = () => {

  const navigate = useNavigate();
  // This will allow us to navigate to the home page once the post is created

  const [form, setForm] = useState({
    name: '',
    prompt:'',
    photo: ''
  })

  const[generatingImg, setGeneratingImg] = useState(false);
  // This is going to be used while we are making contact with our API and while we are waiting to get back the image

  const [loading, setLoading] = useState(false);
  // general loading circle

  const generateImage = async () =>{

    if(form.prompt){

      try { 
        // we are passing all the needed data to the backend to get back the response i.e. AI generated image 
        setGeneratingImg(true);
        const response = await fetch('http://localhost:8080/api/v1/dalle', {
           
           method: 'POST',
           headers: {
            'Content-Type' : 'application/json',
           },
           body: JSON.stringify({ prompt: form.prompt}),
        })
        // the second parameter is an init object that allows you to control a number of different settings.

        // to parse that data and to be able to see it 
        const data = await response.json();
        
        // saving and rendering image 
        setForm({ ...form, photo: `data:image/jpeg;base64,${data.photo}`})
      } catch (error) {
        alert(error);
      } finally{
        setGeneratingImg(false);
      }
    } else{
      alert('Please enter a Prompt')
    }
  }

  const handleSubmit = async (e) => {
     e.preventDefault();
    //  ensures the browser doesnt automatically reloads our application 
     if(form.prompt && form.photo){
        setLoading(true);

        try {
          const response = await fetch('http://localhost:8080/api/v1/post', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(form)
          })

          await response.json();
          navigate('/');
          // going back to home to be able to see our image 

        } catch (error) {
          alert(error)
        } finally{
          setLoading(false);
        }
     } else{
      alert("Please enter a prompt and then generate an image")
     }
  }

  const handleChange=(e)=>{
     setForm({ ...form, [e.target.name] : e.target.value})
  }

  const handleSurpriseMe = () =>{
      const randomPrompt = getRandomPrompt(form.prompt);
      setForm({ ...form, prompt: randomPrompt})
  }

  return (
    <section className="max-w-7xl mx-auto">

      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">Create</h1>

        <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">
          Create a collection of imaginative and visually stunning images generated by DALL-E AI and share them with your peeps ;)
        </p>
      </div>

      <form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>

        <div className="flex flex-col gap-5">
          <FormField
            labelName = "Your name"
            type="text"
            name="name"
            placeholder="Shruti Sharma"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName = "Your prompt"
            type="text"
            name="prompt"
            placeholder="panda mad scientist mixing sparkling chemicals, digital art"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe = {handleSurpriseMe}
          />

          <div className="relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500  focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center">
               {form.photo ? (
                <img 
                  src={form.photo} 
                  alt={form.prompt}
                  className="w-full h-full object-contain"
                />
               ) : (
                <img 
                  src={preview}
                  alt="preview"
                  className="w-9/12 h-9/12 object-contain opacity-40"
                />
               )}

               {/* A loader when the image is being generated  */}
               {generatingImg && (
                <div className="absolute inset-0 z-0 flex  justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg">
                  <Loader/>
                </div>
               )}
          </div>
        </div>
        
        <div className=" mt-5 flex gap-5">
           <button
              type='button'
              onClick={generateImage}
              className="text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center"
           >
              {generatingImg ? 'Generating...' : 'Generate'}
           </button>
        </div>
        <div className="mt-10">
          <p className="mt-2 text-[#666e75] text-[14px]">
            Once you've generated a vv cool picture you wanted, you can also share with your peeps to get the tag of the coolest (which already is yours btw ;)
          </p>
          <button type='submit' className='mt-3 text-white bg-[#6469ff] font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'>
            {loading ? 'Sharing...' : 'Share with your peeps' }
          </button>
        </div>
      </form>

    </section>
  )
}

export default CreatePost
